config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  get 'home/index'
  get 'users/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, except: [:redirect_login]
  before_action :authenticate_user, except: [:index]

  def index
    @user = current_user
    redirect_to projects_path
  end

  def redirect_login
    redirect_to new_user_session
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :redirect_user ]

  # GET /projects or /projects.json
  def index
    @user = current_user
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @user = current_user
  end

  # GET /projects/new
  def new
    @user = current_user
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @user = current_user
  end

  # POST /projects or /projects.json
  def create
    @user = current_user
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
  end

  def redirect_user
    redirect_to new_user_registration
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :porject_description, :on_progress, :starts_on, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_admin!, except: [ :redirect_user ]

    def index
        @user = current_user
        @users = User.all
    end 

    def redirect_user
        redirect_to root
    end

    def authenticate_admin!
        authenticate_user!
        redirect_to :root, status: :forbidden unless current_user.admin?
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning fade show" role="alert">
  <%= notice %>
</div>

app/views/layouts/_navbar.html.erb
<ul class="nav-ul">
  <li class="nav-li">
    <%= link_to "LOGO", root_path %>
    
  </li>
  <% if user_signed_in? %>
    <li class="nav-li"><%= link_to "Edit Profile ", edit_user_registration_path %></li>
    <li class="nav-li"><%= link_to "Projects", projects_path %></li>
    <% if @user.admin %>
    <li class='nav-li'><%= link_to "All Users", users_index_path%> </li>
    <%end%>
    <div class="topnav-right">
      <li class="nav-li"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    </div>
  <% else %>
    <li class="nav-li"><%= link_to "Log In", new_user_session_path %></li>
    <div class="topnav-right">
      <li class="nav-li"><%= link_to "SIGN UP", new_user_registration_path%></li>
    </div>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>ProjectPortal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="alerts-div">
    <% if notice %>
        <%= render 'layouts/alerts' %>
    <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :project_name %><br />
    <%= form.text_field :project_name, class: 'form-control' %>
  </div>
  <br />
  <div class="form-field">
    <%= form.label :porject_description %><br />
    <%= form.text_field :porject_description, class: 'form-control' %>
  </div>
  <br />
  <div class="form-field">
    <%= form.label :on_progress %>
    <%= form.check_box :on_progress, class: 'form-check-input' %>
  </div>
  <br />
  <div class="form-field">
    <%= form.label :starts_on %><br />
    <%= form.date_select :starts_on, class: 'form-control' %>
  </div>
  <br />
  <div class="form-field">
    <%= form.label :user_id %><br />
    <%= form.number_field :user_id, id: :project_user_id, class: 'form-control'  %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit "submit",class: "btn btn-primary"%>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="form-container" >
<h2>Editing Project</h2>

<%= render 'form', project: @project %>
<br/>
<%= link_to 'Show', @project, class: "btn btn-outline-primary btn-sm" %> 
<%= link_to 'Back', projects_path, class: "btn btn-outline-secondary btn-sm" %>
</div>

app/views/projects/index.html.erb
<div class="projects-container">
<h1>PROJECTS</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Project name</th>
      <th>Porject instruction</th>
      <th>On progress</th>
      <th>Started on</th>
      <th >Actions</th>
    </tr>
  </thead>

  <tbody>
    
    <% @projects.each do |project| %>
      <% if project.user_id == current_user.id || current_user.admin %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= project.porject_description %></td>
        <td><%= project.on_progress %></td>
        <td><%= project.starts_on %></td>
        <td><%= link_to 'Show', project,class: "btn btn-outline-primary btn-sm" %>
        <% if @user.admin %>
        <%= link_to 'Edit', edit_project_path(project), class: "btn btn-outline-primary btn-sm" %>
        <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure to delete?' },class: "btn btn-outline-primary btn-sm" %>
        <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if @user.admin %>
  <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
<% end %>  
</div>

app/views/projects/new.html.erb
<div class="form-container" >
<h2>New Project</h2>

<%= render 'form', project: @project %>
<br />
<%= link_to 'Back', projects_path, class: 'btn btn-outline-secondary btn-sm' %>
</div>

app/views/projects/show.html.erb
<div class="card card-custom" >
<div class="card-body card-body-custom"">
  <h2 class="card-title"><%= @project.project_name.upcase %></h2>
  <p class="card-text"><%= @project.porject_description %></p>
  <span class="date-title">Started On : </span><span class='card-date'><%= @project.starts_on%></span><br/><br/>
  <% if @project.on_progress %>
    <button class="btn btn-success btn-lg">On Progress</button>
    <br/><br/>
  <% else %>
    <button class="btn btn-danger">ENDED</button>
    <br/><br/>
  <% end %>
  <% if current_user.admin %>
    <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-outline-primary btn-sm' %>
  <%end%>
  <%= link_to 'Back', projects_path, class: 'btn btn-outline-secondary btn-sm' %>
</div>
</div>

app/views/users/index.html.erb
<div class="projects-container">
<h1>USERS</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>User Id</th>
      <th>User Email</th>
      <th>Joined On</th>
    </tr>
  </thead>

  <tbody>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td><td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>